### ISSUE TITLE
Ошибка запуска: Error: ENOENT: no such file or directory, open 'api_erros.json'

### ISSUE THREAD

**Issue by guminov** [pskucherov/OpexBot#6]
Добрый день,
вообщем не смог запустить ваш бот.

1) по инструкции не запустить, - npm start, ну то ладно, запустил через npm run bot
2) npm run bot - выдал ошибку что нет модуля tinkoff-sdk-grpc-js и ищет он его , почему-то, в tinkofftradingbotconnector/node_modules/tinkoff-sdk-grpc-js

backtester.ts:
import { createSdk } from 'tinkofftradingbotconnector/node_modules/tinkoff-sdk-grpc-js'; - так и должно быть?

3) установил зависимости внутри папку с tinkofftradingbotconnector
4) выдает ошибку Error: ENOENT: no such file or directory, open 'api_erros.json'
файл естественно существует
указал абсолютный путь - таже фигня
поменял import { createSdk } from 'tinkofftradingbotconnector/node_modules/tinkoff-sdk-grpc-js'
на  import { createSdk } from 'tinkoff-sdk-grpc-js' - таже фигня
переименовал /node_modules/tinkoff-sdk-grpc-js/src/errors/api_errors.ts - таже фигня(кеш???)
очистил кеши - таже фигня

я совсем не разбираюсь в TS, так на уровне запустить
в чем проблема?

macos последняя
m1
node -v: v21.2.0

**Comment by pskucherov** [comment]
Здравствуйте
В ближайшие пару часов докину фикс в npm и напишу.

* Известная проблема, произошла когда обновлял API от тинькофф с обновлением файла ошибок.

**Comment by pskucherov** [comment]
Предварительно пофиксил, подтяните последние изменения и попробуйте запустить. Должно заработать.

**Comment by guminov** [comment]
Спасибо, запустил.
Но!)
при открытии  http://localhost:3056/settings и вводе пина - авторизация "срывается" - незаходит

дополню:
на мгновение показывает интерфейс, в верхнем правом углу - Сервер: недоступен

посмотрел куда логин чего отправляет - вроде авторизация на сервере проходит - возвращает токен - верно? 

Разобрался. Не работает с сафари, не знаю почему, зашел через фаирфокс
Это несколько не то чего хотел))

**Comment by pskucherov** [comment]
>  авторизация "срывается" - незаходит

сессии на локалхосте по http на разных портах это отдельная боль. Посмотрю чтобы вообще это убрать на локалхосте.


> Это несколько не то чего хотел))

Смотрели консольную версию?

напишите свои запросы, может смогу помочь. 
Сейчас произошло разделение как раз от пожеланий пользователей, что тем кто умеет программировать UI не нужен. А тем кто не умеет, ничего больше кроме как UI не нужно )

**Comment by pskucherov** [comment]
можно напрямую в телеграм
https://t.me/opexbotru
